# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: AutoUpdate

on:
  schedule:
    - cron: '50,20 14-22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Scrape
      env: # Or as an environment variable
        TWEEPY_SECRETS: ${{ secrets.TWEEPY_SECRETS }}
      run: |
        python src/runscripts.py
    - name: Commit files
      run: |
          git config --local user.email "thomas@tphil.nl"
          git config --local user.name "Thomas (Action)"
          git add .
          git commit -m "Automatic update"
      continue-on-error: true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
      continue-on-error: true
